package pgcode_test

import (
	"testing"

	"github.com/b0r1ssh/pgcode"
)

// TestConstantsMatchCodes verifies every constant has the correct string value.
func TestConstantsMatchCodes(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		got  string
		want string
	}{
		{"SuccessfulCompletion", pgcode.SuccessfulCompletion, "00000"},
		{"Warning", pgcode.Warning, "01000"},
		{"NullValueEliminatedInSetFunction", pgcode.NullValueEliminatedInSetFunction, "01003"},
		{"StringDataRightTruncation", pgcode.StringDataRightTruncation, "01004"},
		{"PrivilegeNotRevoked", pgcode.PrivilegeNotRevoked, "01006"},
		{"PrivilegeNotGranted", pgcode.PrivilegeNotGranted, "01007"},
		{"ImplicitZeroBitPadding", pgcode.ImplicitZeroBitPadding, "01008"},
		{"DynamicResultSetsReturned", pgcode.DynamicResultSetsReturned, "0100C"},
		{"DeprecatedFeature", pgcode.DeprecatedFeature, "01P01"},
		{"NoData", pgcode.NoData, "02000"},
		{"NoAdditionalDynamicResultSetsReturned", pgcode.NoAdditionalDynamicResultSetsReturned, "02001"},
		{"SQLStatementNotYetComplete", pgcode.SQLStatementNotYetComplete, "03000"},
		{"ConnectionException", pgcode.ConnectionException, "08000"},
		{"SqlclientUnableToEstablishSqlconnection", pgcode.SqlclientUnableToEstablishSqlconnection, "08001"},
		{"ConnectionDoesNotExist", pgcode.ConnectionDoesNotExist, "08003"},
		{"SqlserverRejectedEstablishmentOfSqlconnection", pgcode.SqlserverRejectedEstablishmentOfSqlconnection, "08004"},
		{"ConnectionFailure", pgcode.ConnectionFailure, "08006"},
		{"TransactionResolutionUnknown", pgcode.TransactionResolutionUnknown, "08007"},
		{"ProtocolViolation", pgcode.ProtocolViolation, "08P01"},
		{"TriggeredActionException", pgcode.TriggeredActionException, "09000"},
		{"FeatureNotSupported", pgcode.FeatureNotSupported, "0A000"},
		{"InvalidTransactionInitiation", pgcode.InvalidTransactionInitiation, "0B000"},
		{"LocatorException", pgcode.LocatorException, "0F000"},
		{"InvalidLocatorSpecification", pgcode.InvalidLocatorSpecification, "0F001"},
		{"InvalidGrantor", pgcode.InvalidGrantor, "0L000"},
		{"InvalidGrantOperation", pgcode.InvalidGrantOperation, "0LP01"},
		{"InvalidRoleSpecification", pgcode.InvalidRoleSpecification, "0P000"},
		{"DiagnosticsException", pgcode.DiagnosticsException, "0Z000"},
		{"StackedDiagnosticsAccessedWithoutActiveHandler", pgcode.StackedDiagnosticsAccessedWithoutActiveHandler, "0Z002"},
		{"CaseNotFound", pgcode.CaseNotFound, "20000"},
		{"CardinalityViolation", pgcode.CardinalityViolation, "21000"},
		{"DataException", pgcode.DataException, "22000"},
		{"StringDataRightTruncation", pgcode.StringDataRightTruncationClass22, "22001"},
		{"NullValueNoIndicatorParameter", pgcode.NullValueNoIndicatorParameter, "22002"},
		{"NumericValueOutOfRange", pgcode.NumericValueOutOfRange, "22003"},
		{"NullValueNotAllowed", pgcode.NullValueNotAllowed, "22004"},
		{"ErrorInAssignment", pgcode.ErrorInAssignment, "22005"},
		{"InvalidDatetimeFormat", pgcode.InvalidDatetimeFormat, "22007"},
		{"DatetimeFieldOverflow", pgcode.DatetimeFieldOverflow, "22008"},
		{"InvalidTimeZoneDisplacementValue", pgcode.InvalidTimeZoneDisplacementValue, "22009"},
		{"EscapeCharacterConflict", pgcode.EscapeCharacterConflict, "2200B"},
		{"InvalidUseOfEscapeCharacter", pgcode.InvalidUseOfEscapeCharacter, "2200C"},
		{"InvalidEscapeOctet", pgcode.InvalidEscapeOctet, "2200D"},
		{"ZeroLengthCharacterString", pgcode.ZeroLengthCharacterString, "2200F"},
		{"MostSpecificTypeMismatch", pgcode.MostSpecificTypeMismatch, "2200G"},
		{"SequenceGeneratorLimitExceeded", pgcode.SequenceGeneratorLimitExceeded, "2200H"},
		{"NotAnXMLDocument", pgcode.NotAnXMLDocument, "2200L"},
		{"InvalidXMLDocument", pgcode.InvalidXMLDocument, "2200M"},
		{"InvalidXMLContent", pgcode.InvalidXMLContent, "2200N"},
		{"InvalidXMLComment", pgcode.InvalidXMLComment, "2200S"},
		{"InvalidXMLProcessingInstruction", pgcode.InvalidXMLProcessingInstruction, "2200T"},
		{"InvalidIndicatorParameterValue", pgcode.InvalidIndicatorParameterValue, "22010"},
		{"SubstringError", pgcode.SubstringError, "22011"},
		{"DivisionByZero", pgcode.DivisionByZero, "22012"},
		{"InvalidPrecedingOrFollowingSize", pgcode.InvalidPrecedingOrFollowingSize, "22013"},
		{"InvalidArgumentForNtileFunction", pgcode.InvalidArgumentForNtileFunction, "22014"},
		{"IntervalFieldOverflow", pgcode.IntervalFieldOverflow, "22015"},
		{"InvalidArgumentForNthValueFunction", pgcode.InvalidArgumentForNthValueFunction, "22016"},
		{"InvalidCharacterValueForCast", pgcode.InvalidCharacterValueForCast, "22018"},
		{"InvalidEscapeCharacter", pgcode.InvalidEscapeCharacter, "22019"},
		{"InvalidRegularExpression", pgcode.InvalidRegularExpression, "2201B"},
		{"InvalidArgumentForLogarithm", pgcode.InvalidArgumentForLogarithm, "2201E"},
		{"InvalidArgumentForPowerFunction", pgcode.InvalidArgumentForPowerFunction, "2201F"},
		{"InvalidArgumentForWidthBucketFunction", pgcode.InvalidArgumentForWidthBucketFunction, "2201G"},
		{"InvalidRowCountInLimitClause", pgcode.InvalidRowCountInLimitClause, "2201W"},
		{"InvalidRowCountInResultOffsetClause", pgcode.InvalidRowCountInResultOffsetClause, "2201X"},
		{"CharacterNotInRepertoire", pgcode.CharacterNotInRepertoire, "22021"},
		{"IndicatorOverflow", pgcode.IndicatorOverflow, "22022"},
		{"InvalidParameterValue", pgcode.InvalidParameterValue, "22023"},
		{"UnterminatedCString", pgcode.UnterminatedCString, "22024"},
		{"InvalidEscapeSequence", pgcode.InvalidEscapeSequence, "22025"},
		{"StringDataLengthMismatch", pgcode.StringDataLengthMismatch, "22026"},
		{"TrimError", pgcode.TrimError, "22027"},
		{"ArraySubscriptError", pgcode.ArraySubscriptError, "2202E"},
		{"InvalidTablesampleRepeat", pgcode.InvalidTablesampleRepeat, "2202G"},
		{"InvalidTablesampleArgument", pgcode.InvalidTablesampleArgument, "2202H"},
		{"DuplicateJSONObjectKeyValue", pgcode.DuplicateJSONObjectKeyValue, "22030"},
		{"InvalidArgumentForSQLJSONDatetimeFunction", pgcode.InvalidArgumentForSQLJSONDatetimeFunction, "22031"},
		{"InvalidJSONText", pgcode.InvalidJSONText, "22032"},
		{"InvalidSQLJSONSubscript", pgcode.InvalidSQLJSONSubscript, "22033"},
		{"MoreThanOneSQLJSONItem", pgcode.MoreThanOneSQLJSONItem, "22034"},
		{"NoSQLJSONItem", pgcode.NoSQLJSONItem, "22035"},
		{"NonNumericSQLJSONItem", pgcode.NonNumericSQLJSONItem, "22036"},
		{"NonUniqueKeysInAJSONObject", pgcode.NonUniqueKeysInAJSONObject, "22037"},
		{"SingletonSQLJSONItemRequired", pgcode.SingletonSQLJSONItemRequired, "22038"},
		{"SQLJSONArrayNotFound", pgcode.SQLJSONArrayNotFound, "22039"},
		{"SQLJSONMemberNotFound", pgcode.SQLJSONMemberNotFound, "2203A"},
		{"SQLJSONNumberNotFound", pgcode.SQLJSONNumberNotFound, "2203B"},
		{"SQLJSONObjectNotFound", pgcode.SQLJSONObjectNotFound, "2203C"},
		{"TooManyJSONArrayElements", pgcode.TooManyJSONArrayElements, "2203D"},
		{"TooManyJSONObjectMembers", pgcode.TooManyJSONObjectMembers, "2203E"},
		{"SQLJSONScalarRequired", pgcode.SQLJSONScalarRequired, "2203F"},
		{"SQLJSONItemCannotBeCastToTargetType", pgcode.SQLJSONItemCannotBeCastToTargetType, "2203G"},
		{"FloatingPointException", pgcode.FloatingPointException, "22P01"},
		{"InvalidTextRepresentation", pgcode.InvalidTextRepresentation, "22P02"},
		{"InvalidBinaryRepresentation", pgcode.InvalidBinaryRepresentation, "22P03"},
		{"BadCopyFileFormat", pgcode.BadCopyFileFormat, "22P04"},
		{"UntranslatableCharacter", pgcode.UntranslatableCharacter, "22P05"},
		{"NonstandardUseOfEscapeCharacter", pgcode.NonstandardUseOfEscapeCharacter, "22P06"},
		{"IntegrityConstraintViolation", pgcode.IntegrityConstraintViolation, "23000"},
		{"RestrictViolation", pgcode.RestrictViolation, "23001"},
		{"NotNullViolation", pgcode.NotNullViolation, "23502"},
		{"ForeignKeyViolation", pgcode.ForeignKeyViolation, "23503"},
		{"UniqueViolation", pgcode.UniqueViolation, "23505"},
		{"CheckViolation", pgcode.CheckViolation, "23514"},
		{"ExclusionViolation", pgcode.ExclusionViolation, "23P01"},
		{"InvalidCursorState", pgcode.InvalidCursorState, "24000"},
		{"InvalidTransactionState", pgcode.InvalidTransactionState, "25000"},
		{"ActiveSQLTransaction", pgcode.ActiveSQLTransaction, "25001"},
		{"BranchTransactionAlreadyActive", pgcode.BranchTransactionAlreadyActive, "25002"},
		{"InappropriateAccessModeForBranchTransaction", pgcode.InappropriateAccessModeForBranchTransaction, "25003"},
		{"InappropriateIsolationLevelForBranchTransaction", pgcode.InappropriateIsolationLevelForBranchTransaction, "25004"},
		{"NoActiveSQLTransactionForBranchTransaction", pgcode.NoActiveSQLTransactionForBranchTransaction, "25005"},
		{"ReadOnlySQLTransaction", pgcode.ReadOnlySQLTransaction, "25006"},
		{"SchemaAndDataStatementMixingNotSupported", pgcode.SchemaAndDataStatementMixingNotSupported, "25007"},
		{"HeldCursorRequiresSameIsolationLevel", pgcode.HeldCursorRequiresSameIsolationLevel, "25008"},
		{"NoActiveSQLTransaction", pgcode.NoActiveSQLTransaction, "25P01"},
		{"InFailedSQLTransaction", pgcode.InFailedSQLTransaction, "25P02"},
		{"IdleInTransactionSessionTimeout", pgcode.IdleInTransactionSessionTimeout, "25P03"},
		{"TransactionTimeout", pgcode.TransactionTimeout, "25P04"},
		{"InvalidSQLStatementName", pgcode.InvalidSQLStatementName, "26000"},
		{"TriggeredDataChangeViolation", pgcode.TriggeredDataChangeViolation, "27000"},
		{"InvalidAuthorizationSpecification", pgcode.InvalidAuthorizationSpecification, "28000"},
		{"InvalidPassword", pgcode.InvalidPassword, "28P01"},
		{"DependentPrivilegeDescriptorsStillExist", pgcode.DependentPrivilegeDescriptorsStillExist, "2B000"},
		{"DependentObjectsStillExist", pgcode.DependentObjectsStillExist, "2BP01"},
		{"InvalidTransactionTermination", pgcode.InvalidTransactionTermination, "2D000"},
		{"SQLRoutineException", pgcode.SQLRoutineException, "2F000"},
		{"ModifyingSQLDataNotPermitted", pgcode.ModifyingSQLDataNotPermitted, "2F002"},
		{"ProhibitedSQLStatementAttempted", pgcode.ProhibitedSQLStatementAttempted, "2F003"},
		{"ReadingSQLDataNotPermitted", pgcode.ReadingSQLDataNotPermitted, "2F004"},
		{"FunctionExecutedNoReturnStatement", pgcode.FunctionExecutedNoReturnStatement, "2F005"},
		{"InvalidCursorName", pgcode.InvalidCursorName, "34000"},
		{"ExternalRoutineException", pgcode.ExternalRoutineException, "38000"},
		{"ContainingSQLNotPermitted", pgcode.ContainingSQLNotPermitted, "38001"},
		{"ModifyingSQLDataNotPermitted", pgcode.ModifyingSQLDataNotPermittedClass38, "38002"},
		{"ProhibitedSQLStatementAttempted", pgcode.ProhibitedSQLStatementAttemptedClass38, "38003"},
		{"ReadingSQLDataNotPermitted", pgcode.ReadingSQLDataNotPermittedClass38, "38004"},
		{"ExternalRoutineInvocationException", pgcode.ExternalRoutineInvocationException, "39000"},
		{"InvalidSQLStateReturned", pgcode.InvalidSQLStateReturned, "39001"},
		{"NullValueNotAllowed", pgcode.NullValueNotAllowedClass39, "39004"},
		{"TriggerProtocolViolated", pgcode.TriggerProtocolViolated, "39P01"},
		{"SRFProtocolViolated", pgcode.SRFProtocolViolated, "39P02"},
		{"EventTriggerProtocolViolated", pgcode.EventTriggerProtocolViolated, "39P03"},
		{"SavepointException", pgcode.SavepointException, "3B000"},
		{"InvalidSavepointSpecification", pgcode.InvalidSavepointSpecification, "3B001"},
		{"InvalidCatalogName", pgcode.InvalidCatalogName, "3D000"},
		{"InvalidSchemaName", pgcode.InvalidSchemaName, "3F000"},
		{"TransactionRollback", pgcode.TransactionRollback, "40000"},
		{"SerializationFailure", pgcode.SerializationFailure, "40001"},
		{"TransactionIntegrityConstraintViolation", pgcode.TransactionIntegrityConstraintViolation, "40002"},
		{"StatementCompletionUnknown", pgcode.StatementCompletionUnknown, "40003"},
		{"DeadlockDetected", pgcode.DeadlockDetected, "40P01"},
		{"SyntaxErrorOrAccessRuleViolation", pgcode.SyntaxErrorOrAccessRuleViolation, "42000"},
		{"InsufficientPrivilege", pgcode.InsufficientPrivilege, "42501"},
		{"SyntaxError", pgcode.SyntaxError, "42601"},
		{"InvalidName", pgcode.InvalidName, "42602"},
		{"InvalidColumnDefinition", pgcode.InvalidColumnDefinition, "42611"},
		{"NameTooLong", pgcode.NameTooLong, "42622"},
		{"DuplicateColumn", pgcode.DuplicateColumn, "42701"},
		{"AmbiguousColumn", pgcode.AmbiguousColumn, "42702"},
		{"UndefinedColumn", pgcode.UndefinedColumn, "42703"},
		{"UndefinedObject", pgcode.UndefinedObject, "42704"},
		{"DuplicateObject", pgcode.DuplicateObject, "42710"},
		{"DuplicateAlias", pgcode.DuplicateAlias, "42712"},
		{"DuplicateFunction", pgcode.DuplicateFunction, "42723"},
		{"AmbiguousFunction", pgcode.AmbiguousFunction, "42725"},
		{"GroupingError", pgcode.GroupingError, "42803"},
		{"DatatypeMismatch", pgcode.DatatypeMismatch, "42804"},
		{"WrongObjectType", pgcode.WrongObjectType, "42809"},
		{"InvalidForeignKey", pgcode.InvalidForeignKey, "42830"},
		{"CannotCoerce", pgcode.CannotCoerce, "42846"},
		{"UndefinedFunction", pgcode.UndefinedFunction, "42883"},
		{"GeneratedAlways", pgcode.GeneratedAlways, "428C9"},
		{"ReservedName", pgcode.ReservedName, "42939"},
		{"UndefinedTable", pgcode.UndefinedTable, "42P01"},
		{"UndefinedParameter", pgcode.UndefinedParameter, "42P02"},
		{"DuplicateCursor", pgcode.DuplicateCursor, "42P03"},
		{"DuplicateDatabase", pgcode.DuplicateDatabase, "42P04"},
		{"DuplicatePreparedStatement", pgcode.DuplicatePreparedStatement, "42P05"},
		{"DuplicateSchema", pgcode.DuplicateSchema, "42P06"},
		{"DuplicateTable", pgcode.DuplicateTable, "42P07"},
		{"AmbiguousParameter", pgcode.AmbiguousParameter, "42P08"},
		{"AmbiguousAlias", pgcode.AmbiguousAlias, "42P09"},
		{"InvalidColumnReference", pgcode.InvalidColumnReference, "42P10"},
		{"InvalidCursorDefinition", pgcode.InvalidCursorDefinition, "42P11"},
		{"InvalidDatabaseDefinition", pgcode.InvalidDatabaseDefinition, "42P12"},
		{"InvalidFunctionDefinition", pgcode.InvalidFunctionDefinition, "42P13"},
		{"InvalidPreparedStatementDefinition", pgcode.InvalidPreparedStatementDefinition, "42P14"},
		{"InvalidSchemaDefinition", pgcode.InvalidSchemaDefinition, "42P15"},
		{"InvalidTableDefinition", pgcode.InvalidTableDefinition, "42P16"},
		{"InvalidObjectDefinition", pgcode.InvalidObjectDefinition, "42P17"},
		{"IndeterminateDatatype", pgcode.IndeterminateDatatype, "42P18"},
		{"InvalidRecursion", pgcode.InvalidRecursion, "42P19"},
		{"WindowingError", pgcode.WindowingError, "42P20"},
		{"CollationMismatch", pgcode.CollationMismatch, "42P21"},
		{"IndeterminateCollation", pgcode.IndeterminateCollation, "42P22"},
		{"WithCheckOptionViolation", pgcode.WithCheckOptionViolation, "44000"},
		{"InsufficientResources", pgcode.InsufficientResources, "53000"},
		{"DiskFull", pgcode.DiskFull, "53100"},
		{"OutOfMemory", pgcode.OutOfMemory, "53200"},
		{"TooManyConnections", pgcode.TooManyConnections, "53300"},
		{"ConfigurationLimitExceeded", pgcode.ConfigurationLimitExceeded, "53400"},
		{"ProgramLimitExceeded", pgcode.ProgramLimitExceeded, "54000"},
		{"StatementTooComplex", pgcode.StatementTooComplex, "54001"},
		{"TooManyColumns", pgcode.TooManyColumns, "54011"},
		{"TooManyArguments", pgcode.TooManyArguments, "54023"},
		{"ObjectNotInPrerequisiteState", pgcode.ObjectNotInPrerequisiteState, "55000"},
		{"ObjectInUse", pgcode.ObjectInUse, "55006"},
		{"CantChangeRuntimeParam", pgcode.CantChangeRuntimeParam, "55P02"},
		{"LockNotAvailable", pgcode.LockNotAvailable, "55P03"},
		{"UnsafeNewEnumValueUsage", pgcode.UnsafeNewEnumValueUsage, "55P04"},
		{"OperatorIntervention", pgcode.OperatorIntervention, "57000"},
		{"QueryCanceled", pgcode.QueryCanceled, "57014"},
		{"AdminShutdown", pgcode.AdminShutdown, "57P01"},
		{"CrashShutdown", pgcode.CrashShutdown, "57P02"},
		{"CannotConnectNow", pgcode.CannotConnectNow, "57P03"},
		{"DatabaseDropped", pgcode.DatabaseDropped, "57P04"},
		{"IdleSessionTimeout", pgcode.IdleSessionTimeout, "57P05"},
		{"SystemError", pgcode.SystemError, "58000"},
		{"IOError", pgcode.IOError, "58030"},
		{"UndefinedFile", pgcode.UndefinedFile, "58P01"},
		{"DuplicateFile", pgcode.DuplicateFile, "58P02"},
		{"FileNameTooLong", pgcode.FileNameTooLong, "58P03"},
		{"SnapshotTooOld", pgcode.SnapshotTooOld, "72000"},
		{"ConfigFileError", pgcode.ConfigFileError, "F0000"},
		{"LockFileExists", pgcode.LockFileExists, "F0001"},
		{"FDWError", pgcode.FDWError, "HV000"},
		{"FDWOutOfMemory", pgcode.FDWOutOfMemory, "HV001"},
		{"FDWDynamicParameterValueNeeded", pgcode.FDWDynamicParameterValueNeeded, "HV002"},
		{"FDWInvalidDataType", pgcode.FDWInvalidDataType, "HV004"},
		{"FDWColumnNameNotFound", pgcode.FDWColumnNameNotFound, "HV005"},
		{"FDWInvalidDataTypeDescriptors", pgcode.FDWInvalidDataTypeDescriptors, "HV006"},
		{"FDWInvalidColumnName", pgcode.FDWInvalidColumnName, "HV007"},
		{"FDWInvalidColumnNumber", pgcode.FDWInvalidColumnNumber, "HV008"},
		{"FDWInvalidUseOfNullPointer", pgcode.FDWInvalidUseOfNullPointer, "HV009"},
		{"FDWInvalidStringFormat", pgcode.FDWInvalidStringFormat, "HV00A"},
		{"FDWInvalidHandle", pgcode.FDWInvalidHandle, "HV00B"},
		{"FDWInvalidOptionIndex", pgcode.FDWInvalidOptionIndex, "HV00C"},
		{"FDWInvalidOptionName", pgcode.FDWInvalidOptionName, "HV00D"},
		{"FDWOptionNameNotFound", pgcode.FDWOptionNameNotFound, "HV00J"},
		{"FDWReplyHandle", pgcode.FDWReplyHandle, "HV00K"},
		{"FDWUnableToCreateExecution", pgcode.FDWUnableToCreateExecution, "HV00L"},
		{"FDWUnableToCreateReply", pgcode.FDWUnableToCreateReply, "HV00M"},
		{"FDWUnableToEstablishConnection", pgcode.FDWUnableToEstablishConnection, "HV00N"},
		{"FDWNoSchemas", pgcode.FDWNoSchemas, "HV00P"},
		{"FDWSchemaNotFound", pgcode.FDWSchemaNotFound, "HV00Q"},
		{"FDWTableNotFound", pgcode.FDWTableNotFound, "HV00R"},
		{"FDWFunctionSequenceError", pgcode.FDWFunctionSequenceError, "HV010"},
		{"FDWTooManyHandles", pgcode.FDWTooManyHandles, "HV014"},
		{"FDWInconsistentDescriptorInformation", pgcode.FDWInconsistentDescriptorInformation, "HV021"},
		{"FDWInvalidAttributeValue", pgcode.FDWInvalidAttributeValue, "HV024"},
		{"FDWInvalidStringLengthOrBufferLength", pgcode.FDWInvalidStringLengthOrBufferLength, "HV090"},
		{"FDWInvalidDescriptorFieldIdentifier", pgcode.FDWInvalidDescriptorFieldIdentifier, "HV091"},
		{"PLpgSQLError", pgcode.PLpgSQLError, "P0000"},
		{"RaiseException", pgcode.RaiseException, "P0001"},
		{"NoDataFound", pgcode.NoDataFound, "P0002"},
		{"TooManyRows", pgcode.TooManyRows, "P0003"},
		{"AssertFailure", pgcode.AssertFailure, "P0004"},
		{"InternalError", pgcode.InternalError, "XX000"},
		{"DataCorrupted", pgcode.DataCorrupted, "XX001"},
		{"IndexCorrupted", pgcode.IndexCorrupted, "XX002"},
		{"InvalidArgumentForXquery", pgcode.InvalidArgumentForXquery, "10608"},
	}
	for _, tt := range tests {
		if tt.got != tt.want {
			t.Errorf("pgcode.%s = %q, want %q", tt.name, tt.got, tt.want)
		}
	}
}

// TestIsXxxFunctions verifies each IsXxx function accepts all codes in its class
// and rejects codes from other classes.
func TestIsXxxFunctions(t *testing.T) {
	t.Parallel()

	tests := []struct {
		fn      string
		is      func(string) bool
		members []string
	}{
		{
			fn:      "IsSuccessfulCompletion",
			is:      pgcode.IsSuccessfulCompletion,
			members: []string{"00000"},
		},
		{
			fn:      "IsWarning",
			is:      pgcode.IsWarning,
			members: []string{"01000", "01003", "01004", "01006", "01007", "01008", "0100C", "01P01"},
		},
		{
			fn:      "IsNoData",
			is:      pgcode.IsNoData,
			members: []string{"02000", "02001"},
		},
		{
			fn:      "IsSqlStatementNotYetComplete",
			is:      pgcode.IsSqlStatementNotYetComplete,
			members: []string{"03000"},
		},
		{
			fn:      "IsConnectionException",
			is:      pgcode.IsConnectionException,
			members: []string{"08000", "08001", "08003", "08004", "08006", "08007", "08P01"},
		},
		{
			fn:      "IsTriggeredActionException",
			is:      pgcode.IsTriggeredActionException,
			members: []string{"09000"},
		},
		{
			fn:      "IsFeatureNotSupported",
			is:      pgcode.IsFeatureNotSupported,
			members: []string{"0A000"},
		},
		{
			fn:      "IsInvalidTransactionInitiation",
			is:      pgcode.IsInvalidTransactionInitiation,
			members: []string{"0B000"},
		},
		{
			fn:      "IsLocatorException",
			is:      pgcode.IsLocatorException,
			members: []string{"0F000", "0F001"},
		},
		{
			fn:      "IsInvalidGrantor",
			is:      pgcode.IsInvalidGrantor,
			members: []string{"0L000", "0LP01"},
		},
		{
			fn:      "IsInvalidRoleSpecification",
			is:      pgcode.IsInvalidRoleSpecification,
			members: []string{"0P000"},
		},
		{
			fn:      "IsDiagnosticsException",
			is:      pgcode.IsDiagnosticsException,
			members: []string{"0Z000", "0Z002"},
		},
		{
			fn:      "IsCaseNotFound",
			is:      pgcode.IsCaseNotFound,
			members: []string{"20000"},
		},
		{
			fn:      "IsCardinalityViolation",
			is:      pgcode.IsCardinalityViolation,
			members: []string{"21000"},
		},
		{
			fn:      "IsDataException",
			is:      pgcode.IsDataException,
			members: []string{"22000", "22001", "22002", "22003", "22004", "22005", "22007", "22008", "22009", "2200B", "2200C", "2200D", "2200F", "2200G", "2200H", "2200L", "2200M", "2200N", "2200S", "2200T", "22010", "22011", "22012", "22013", "22014", "22015", "22016", "22018", "22019", "2201B", "2201E", "2201F", "2201G", "2201W", "2201X", "22021", "22022", "22023", "22024", "22025", "22026", "22027", "2202E", "2202G", "2202H", "22030", "22031", "22032", "22033", "22034", "22035", "22036", "22037", "22038", "22039", "2203A", "2203B", "2203C", "2203D", "2203E", "2203F", "2203G", "22P01", "22P02", "22P03", "22P04", "22P05", "22P06"},
		},
		{
			fn:      "IsIntegrityConstraintViolation",
			is:      pgcode.IsIntegrityConstraintViolation,
			members: []string{"23000", "23001", "23502", "23503", "23505", "23514", "23P01"},
		},
		{
			fn:      "IsInvalidCursorState",
			is:      pgcode.IsInvalidCursorState,
			members: []string{"24000"},
		},
		{
			fn:      "IsInvalidTransactionState",
			is:      pgcode.IsInvalidTransactionState,
			members: []string{"25000", "25001", "25002", "25003", "25004", "25005", "25006", "25007", "25008", "25P01", "25P02", "25P03", "25P04"},
		},
		{
			fn:      "IsInvalidSqlStatementName",
			is:      pgcode.IsInvalidSqlStatementName,
			members: []string{"26000"},
		},
		{
			fn:      "IsTriggeredDataChangeViolation",
			is:      pgcode.IsTriggeredDataChangeViolation,
			members: []string{"27000"},
		},
		{
			fn:      "IsInvalidAuthorizationSpecification",
			is:      pgcode.IsInvalidAuthorizationSpecification,
			members: []string{"28000", "28P01"},
		},
		{
			fn:      "IsDependentPrivilegeDescriptorsStillExist",
			is:      pgcode.IsDependentPrivilegeDescriptorsStillExist,
			members: []string{"2B000", "2BP01"},
		},
		{
			fn:      "IsInvalidTransactionTermination",
			is:      pgcode.IsInvalidTransactionTermination,
			members: []string{"2D000"},
		},
		{
			fn:      "IsSqlRoutineException",
			is:      pgcode.IsSqlRoutineException,
			members: []string{"2F000", "2F002", "2F003", "2F004", "2F005"},
		},
		{
			fn:      "IsInvalidCursorName",
			is:      pgcode.IsInvalidCursorName,
			members: []string{"34000"},
		},
		{
			fn:      "IsExternalRoutineException",
			is:      pgcode.IsExternalRoutineException,
			members: []string{"38000", "38001", "38002", "38003", "38004"},
		},
		{
			fn:      "IsExternalRoutineInvocationException",
			is:      pgcode.IsExternalRoutineInvocationException,
			members: []string{"39000", "39001", "39004", "39P01", "39P02", "39P03"},
		},
		{
			fn:      "IsSavepointException",
			is:      pgcode.IsSavepointException,
			members: []string{"3B000", "3B001"},
		},
		{
			fn:      "IsInvalidCatalogName",
			is:      pgcode.IsInvalidCatalogName,
			members: []string{"3D000"},
		},
		{
			fn:      "IsInvalidSchemaName",
			is:      pgcode.IsInvalidSchemaName,
			members: []string{"3F000"},
		},
		{
			fn:      "IsTransactionRollback",
			is:      pgcode.IsTransactionRollback,
			members: []string{"40000", "40001", "40002", "40003", "40P01"},
		},
		{
			fn:      "IsSyntaxErrorOrAccessRuleViolation",
			is:      pgcode.IsSyntaxErrorOrAccessRuleViolation,
			members: []string{"42000", "42501", "42601", "42602", "42611", "42622", "42701", "42702", "42703", "42704", "42710", "42712", "42723", "42725", "42803", "42804", "42809", "42830", "42846", "42883", "428C9", "42939", "42P01", "42P02", "42P03", "42P04", "42P05", "42P06", "42P07", "42P08", "42P09", "42P10", "42P11", "42P12", "42P13", "42P14", "42P15", "42P16", "42P17", "42P18", "42P19", "42P20", "42P21", "42P22"},
		},
		{
			fn:      "IsWithCheckOptionViolation",
			is:      pgcode.IsWithCheckOptionViolation,
			members: []string{"44000"},
		},
		{
			fn:      "IsInsufficientResources",
			is:      pgcode.IsInsufficientResources,
			members: []string{"53000", "53100", "53200", "53300", "53400"},
		},
		{
			fn:      "IsProgramLimitExceeded",
			is:      pgcode.IsProgramLimitExceeded,
			members: []string{"54000", "54001", "54011", "54023"},
		},
		{
			fn:      "IsObjectNotInPrerequisiteState",
			is:      pgcode.IsObjectNotInPrerequisiteState,
			members: []string{"55000", "55006", "55P02", "55P03", "55P04"},
		},
		{
			fn:      "IsOperatorIntervention",
			is:      pgcode.IsOperatorIntervention,
			members: []string{"57000", "57014", "57P01", "57P02", "57P03", "57P04", "57P05"},
		},
		{
			fn:      "IsSystemError",
			is:      pgcode.IsSystemError,
			members: []string{"58000", "58030", "58P01", "58P02", "58P03"},
		},
		{
			fn:      "IsSnapshotFailure",
			is:      pgcode.IsSnapshotFailure,
			members: []string{"72000"},
		},
		{
			fn:      "IsConfigurationFileError",
			is:      pgcode.IsConfigurationFileError,
			members: []string{"F0000", "F0001"},
		},
		{
			fn:      "IsForeignDataWrapperError",
			is:      pgcode.IsForeignDataWrapperError,
			members: []string{"HV000", "HV001", "HV002", "HV004", "HV005", "HV006", "HV007", "HV008", "HV009", "HV00A", "HV00B", "HV00C", "HV00D", "HV00J", "HV00K", "HV00L", "HV00M", "HV00N", "HV00P", "HV00Q", "HV00R", "HV010", "HV014", "HV021", "HV024", "HV090", "HV091"},
		},
		{
			fn:      "IsPl",
			is:      pgcode.IsPl,
			members: []string{"P0000", "P0001", "P0002", "P0003", "P0004"},
		},
		{
			fn:      "IsInternalError",
			is:      pgcode.IsInternalError,
			members: []string{"XX000", "XX001", "XX002"},
		},
		{
			fn:      "IsXqueryError",
			is:      pgcode.IsXqueryError,
			members: []string{"10608"},
		},
	}

	// Build a set of all codes per function for cross-rejection testing.
	for _, tt := range tests {
		for _, code := range tt.members {
			if !tt.is(code) {
				t.Errorf("%s(%q) = false, want true", tt.fn, code)
			}
		}
	}

	// Each function must reject codes that belong to other classes.
	for i, tt := range tests {
		for j, other := range tests {
			if i == j {
				continue
			}
			for _, code := range other.members {
				if tt.is(code) {
					t.Errorf("%s(%q) = true, want false (code belongs to %s)", tt.fn, code, other.fn)
				}
			}
		}
	}
}

// TestNameRoundtrip verifies Name() returns the constant name for every code.
func TestNameRoundtrip(t *testing.T) {
	t.Parallel()

	tests := []struct {
		code string
		want string
	}{
		{"00000", "SuccessfulCompletion"},
		{"01000", "Warning"},
		{"01003", "NullValueEliminatedInSetFunction"},
		{"01004", "StringDataRightTruncation"},
		{"01006", "PrivilegeNotRevoked"},
		{"01007", "PrivilegeNotGranted"},
		{"01008", "ImplicitZeroBitPadding"},
		{"0100C", "DynamicResultSetsReturned"},
		{"01P01", "DeprecatedFeature"},
		{"02000", "NoData"},
		{"02001", "NoAdditionalDynamicResultSetsReturned"},
		{"03000", "SQLStatementNotYetComplete"},
		{"08000", "ConnectionException"},
		{"08001", "SqlclientUnableToEstablishSqlconnection"},
		{"08003", "ConnectionDoesNotExist"},
		{"08004", "SqlserverRejectedEstablishmentOfSqlconnection"},
		{"08006", "ConnectionFailure"},
		{"08007", "TransactionResolutionUnknown"},
		{"08P01", "ProtocolViolation"},
		{"09000", "TriggeredActionException"},
		{"0A000", "FeatureNotSupported"},
		{"0B000", "InvalidTransactionInitiation"},
		{"0F000", "LocatorException"},
		{"0F001", "InvalidLocatorSpecification"},
		{"0L000", "InvalidGrantor"},
		{"0LP01", "InvalidGrantOperation"},
		{"0P000", "InvalidRoleSpecification"},
		{"0Z000", "DiagnosticsException"},
		{"0Z002", "StackedDiagnosticsAccessedWithoutActiveHandler"},
		{"20000", "CaseNotFound"},
		{"21000", "CardinalityViolation"},
		{"22000", "DataException"},
		{"22001", "StringDataRightTruncation"},
		{"22002", "NullValueNoIndicatorParameter"},
		{"22003", "NumericValueOutOfRange"},
		{"22004", "NullValueNotAllowed"},
		{"22005", "ErrorInAssignment"},
		{"22007", "InvalidDatetimeFormat"},
		{"22008", "DatetimeFieldOverflow"},
		{"22009", "InvalidTimeZoneDisplacementValue"},
		{"2200B", "EscapeCharacterConflict"},
		{"2200C", "InvalidUseOfEscapeCharacter"},
		{"2200D", "InvalidEscapeOctet"},
		{"2200F", "ZeroLengthCharacterString"},
		{"2200G", "MostSpecificTypeMismatch"},
		{"2200H", "SequenceGeneratorLimitExceeded"},
		{"2200L", "NotAnXMLDocument"},
		{"2200M", "InvalidXMLDocument"},
		{"2200N", "InvalidXMLContent"},
		{"2200S", "InvalidXMLComment"},
		{"2200T", "InvalidXMLProcessingInstruction"},
		{"22010", "InvalidIndicatorParameterValue"},
		{"22011", "SubstringError"},
		{"22012", "DivisionByZero"},
		{"22013", "InvalidPrecedingOrFollowingSize"},
		{"22014", "InvalidArgumentForNtileFunction"},
		{"22015", "IntervalFieldOverflow"},
		{"22016", "InvalidArgumentForNthValueFunction"},
		{"22018", "InvalidCharacterValueForCast"},
		{"22019", "InvalidEscapeCharacter"},
		{"2201B", "InvalidRegularExpression"},
		{"2201E", "InvalidArgumentForLogarithm"},
		{"2201F", "InvalidArgumentForPowerFunction"},
		{"2201G", "InvalidArgumentForWidthBucketFunction"},
		{"2201W", "InvalidRowCountInLimitClause"},
		{"2201X", "InvalidRowCountInResultOffsetClause"},
		{"22021", "CharacterNotInRepertoire"},
		{"22022", "IndicatorOverflow"},
		{"22023", "InvalidParameterValue"},
		{"22024", "UnterminatedCString"},
		{"22025", "InvalidEscapeSequence"},
		{"22026", "StringDataLengthMismatch"},
		{"22027", "TrimError"},
		{"2202E", "ArraySubscriptError"},
		{"2202G", "InvalidTablesampleRepeat"},
		{"2202H", "InvalidTablesampleArgument"},
		{"22030", "DuplicateJSONObjectKeyValue"},
		{"22031", "InvalidArgumentForSQLJSONDatetimeFunction"},
		{"22032", "InvalidJSONText"},
		{"22033", "InvalidSQLJSONSubscript"},
		{"22034", "MoreThanOneSQLJSONItem"},
		{"22035", "NoSQLJSONItem"},
		{"22036", "NonNumericSQLJSONItem"},
		{"22037", "NonUniqueKeysInAJSONObject"},
		{"22038", "SingletonSQLJSONItemRequired"},
		{"22039", "SQLJSONArrayNotFound"},
		{"2203A", "SQLJSONMemberNotFound"},
		{"2203B", "SQLJSONNumberNotFound"},
		{"2203C", "SQLJSONObjectNotFound"},
		{"2203D", "TooManyJSONArrayElements"},
		{"2203E", "TooManyJSONObjectMembers"},
		{"2203F", "SQLJSONScalarRequired"},
		{"2203G", "SQLJSONItemCannotBeCastToTargetType"},
		{"22P01", "FloatingPointException"},
		{"22P02", "InvalidTextRepresentation"},
		{"22P03", "InvalidBinaryRepresentation"},
		{"22P04", "BadCopyFileFormat"},
		{"22P05", "UntranslatableCharacter"},
		{"22P06", "NonstandardUseOfEscapeCharacter"},
		{"23000", "IntegrityConstraintViolation"},
		{"23001", "RestrictViolation"},
		{"23502", "NotNullViolation"},
		{"23503", "ForeignKeyViolation"},
		{"23505", "UniqueViolation"},
		{"23514", "CheckViolation"},
		{"23P01", "ExclusionViolation"},
		{"24000", "InvalidCursorState"},
		{"25000", "InvalidTransactionState"},
		{"25001", "ActiveSQLTransaction"},
		{"25002", "BranchTransactionAlreadyActive"},
		{"25003", "InappropriateAccessModeForBranchTransaction"},
		{"25004", "InappropriateIsolationLevelForBranchTransaction"},
		{"25005", "NoActiveSQLTransactionForBranchTransaction"},
		{"25006", "ReadOnlySQLTransaction"},
		{"25007", "SchemaAndDataStatementMixingNotSupported"},
		{"25008", "HeldCursorRequiresSameIsolationLevel"},
		{"25P01", "NoActiveSQLTransaction"},
		{"25P02", "InFailedSQLTransaction"},
		{"25P03", "IdleInTransactionSessionTimeout"},
		{"25P04", "TransactionTimeout"},
		{"26000", "InvalidSQLStatementName"},
		{"27000", "TriggeredDataChangeViolation"},
		{"28000", "InvalidAuthorizationSpecification"},
		{"28P01", "InvalidPassword"},
		{"2B000", "DependentPrivilegeDescriptorsStillExist"},
		{"2BP01", "DependentObjectsStillExist"},
		{"2D000", "InvalidTransactionTermination"},
		{"2F000", "SQLRoutineException"},
		{"2F002", "ModifyingSQLDataNotPermitted"},
		{"2F003", "ProhibitedSQLStatementAttempted"},
		{"2F004", "ReadingSQLDataNotPermitted"},
		{"2F005", "FunctionExecutedNoReturnStatement"},
		{"34000", "InvalidCursorName"},
		{"38000", "ExternalRoutineException"},
		{"38001", "ContainingSQLNotPermitted"},
		{"38002", "ModifyingSQLDataNotPermitted"},
		{"38003", "ProhibitedSQLStatementAttempted"},
		{"38004", "ReadingSQLDataNotPermitted"},
		{"39000", "ExternalRoutineInvocationException"},
		{"39001", "InvalidSQLStateReturned"},
		{"39004", "NullValueNotAllowed"},
		{"39P01", "TriggerProtocolViolated"},
		{"39P02", "SRFProtocolViolated"},
		{"39P03", "EventTriggerProtocolViolated"},
		{"3B000", "SavepointException"},
		{"3B001", "InvalidSavepointSpecification"},
		{"3D000", "InvalidCatalogName"},
		{"3F000", "InvalidSchemaName"},
		{"40000", "TransactionRollback"},
		{"40001", "SerializationFailure"},
		{"40002", "TransactionIntegrityConstraintViolation"},
		{"40003", "StatementCompletionUnknown"},
		{"40P01", "DeadlockDetected"},
		{"42000", "SyntaxErrorOrAccessRuleViolation"},
		{"42501", "InsufficientPrivilege"},
		{"42601", "SyntaxError"},
		{"42602", "InvalidName"},
		{"42611", "InvalidColumnDefinition"},
		{"42622", "NameTooLong"},
		{"42701", "DuplicateColumn"},
		{"42702", "AmbiguousColumn"},
		{"42703", "UndefinedColumn"},
		{"42704", "UndefinedObject"},
		{"42710", "DuplicateObject"},
		{"42712", "DuplicateAlias"},
		{"42723", "DuplicateFunction"},
		{"42725", "AmbiguousFunction"},
		{"42803", "GroupingError"},
		{"42804", "DatatypeMismatch"},
		{"42809", "WrongObjectType"},
		{"42830", "InvalidForeignKey"},
		{"42846", "CannotCoerce"},
		{"42883", "UndefinedFunction"},
		{"428C9", "GeneratedAlways"},
		{"42939", "ReservedName"},
		{"42P01", "UndefinedTable"},
		{"42P02", "UndefinedParameter"},
		{"42P03", "DuplicateCursor"},
		{"42P04", "DuplicateDatabase"},
		{"42P05", "DuplicatePreparedStatement"},
		{"42P06", "DuplicateSchema"},
		{"42P07", "DuplicateTable"},
		{"42P08", "AmbiguousParameter"},
		{"42P09", "AmbiguousAlias"},
		{"42P10", "InvalidColumnReference"},
		{"42P11", "InvalidCursorDefinition"},
		{"42P12", "InvalidDatabaseDefinition"},
		{"42P13", "InvalidFunctionDefinition"},
		{"42P14", "InvalidPreparedStatementDefinition"},
		{"42P15", "InvalidSchemaDefinition"},
		{"42P16", "InvalidTableDefinition"},
		{"42P17", "InvalidObjectDefinition"},
		{"42P18", "IndeterminateDatatype"},
		{"42P19", "InvalidRecursion"},
		{"42P20", "WindowingError"},
		{"42P21", "CollationMismatch"},
		{"42P22", "IndeterminateCollation"},
		{"44000", "WithCheckOptionViolation"},
		{"53000", "InsufficientResources"},
		{"53100", "DiskFull"},
		{"53200", "OutOfMemory"},
		{"53300", "TooManyConnections"},
		{"53400", "ConfigurationLimitExceeded"},
		{"54000", "ProgramLimitExceeded"},
		{"54001", "StatementTooComplex"},
		{"54011", "TooManyColumns"},
		{"54023", "TooManyArguments"},
		{"55000", "ObjectNotInPrerequisiteState"},
		{"55006", "ObjectInUse"},
		{"55P02", "CantChangeRuntimeParam"},
		{"55P03", "LockNotAvailable"},
		{"55P04", "UnsafeNewEnumValueUsage"},
		{"57000", "OperatorIntervention"},
		{"57014", "QueryCanceled"},
		{"57P01", "AdminShutdown"},
		{"57P02", "CrashShutdown"},
		{"57P03", "CannotConnectNow"},
		{"57P04", "DatabaseDropped"},
		{"57P05", "IdleSessionTimeout"},
		{"58000", "SystemError"},
		{"58030", "IOError"},
		{"58P01", "UndefinedFile"},
		{"58P02", "DuplicateFile"},
		{"58P03", "FileNameTooLong"},
		{"72000", "SnapshotTooOld"},
		{"F0000", "ConfigFileError"},
		{"F0001", "LockFileExists"},
		{"HV000", "FDWError"},
		{"HV001", "FDWOutOfMemory"},
		{"HV002", "FDWDynamicParameterValueNeeded"},
		{"HV004", "FDWInvalidDataType"},
		{"HV005", "FDWColumnNameNotFound"},
		{"HV006", "FDWInvalidDataTypeDescriptors"},
		{"HV007", "FDWInvalidColumnName"},
		{"HV008", "FDWInvalidColumnNumber"},
		{"HV009", "FDWInvalidUseOfNullPointer"},
		{"HV00A", "FDWInvalidStringFormat"},
		{"HV00B", "FDWInvalidHandle"},
		{"HV00C", "FDWInvalidOptionIndex"},
		{"HV00D", "FDWInvalidOptionName"},
		{"HV00J", "FDWOptionNameNotFound"},
		{"HV00K", "FDWReplyHandle"},
		{"HV00L", "FDWUnableToCreateExecution"},
		{"HV00M", "FDWUnableToCreateReply"},
		{"HV00N", "FDWUnableToEstablishConnection"},
		{"HV00P", "FDWNoSchemas"},
		{"HV00Q", "FDWSchemaNotFound"},
		{"HV00R", "FDWTableNotFound"},
		{"HV010", "FDWFunctionSequenceError"},
		{"HV014", "FDWTooManyHandles"},
		{"HV021", "FDWInconsistentDescriptorInformation"},
		{"HV024", "FDWInvalidAttributeValue"},
		{"HV090", "FDWInvalidStringLengthOrBufferLength"},
		{"HV091", "FDWInvalidDescriptorFieldIdentifier"},
		{"P0000", "PLpgSQLError"},
		{"P0001", "RaiseException"},
		{"P0002", "NoDataFound"},
		{"P0003", "TooManyRows"},
		{"P0004", "AssertFailure"},
		{"XX000", "InternalError"},
		{"XX001", "DataCorrupted"},
		{"XX002", "IndexCorrupted"},
		{"10608", "InvalidArgumentForXquery"},
	}
	for _, tt := range tests {
		if got := pgcode.Name(tt.code); got != tt.want {
			t.Errorf("Name(%q) = %q, want %q", tt.code, got, tt.want)
		}
	}
}

// TestNameUnknown verifies Name() returns empty string for unknown codes.
func TestNameUnknown(t *testing.T) {
	t.Parallel()

	unknown := []string{"", "99999", "ZZZZZ", "00001"}
	for _, code := range unknown {
		if got := pgcode.Name(code); got != "" {
			t.Errorf("Name(%q) = %q, want empty string", code, got)
		}
	}
}
